# Generated by Django 2.0.13 on 2019-05-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('updatedOnVersion', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Modalities',
            },
        ),
    ]
