# Generated by Django 2.0.13 on 2019-05-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField()),
            ],
        ),
    ]
