# Generated by Django 2.0.13 on 2019-05-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190527_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anatomicalregion',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='anatomyimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
        migrations.AddField(
            model_name='anatomicalregion',
            name='updatedOnVersion',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='anatomyimage',
            name='updatedOnVersion',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='updatedOnVersion',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updatedOnVersion',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='updatedOnVersion',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='modality',
            name='updatedOnVersion',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
